[View in Colaboratory](https://colab.research.google.com/github/harsh199910/ml-google/blob/master/Untitled2.ipynb)

In [17]:
from __future__ import print_function

import pandas as pd
import math

from matplotlib import cm
from IPython import display
from matplotlib import gridspec
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
from sklearn import metrics
import tensorflow as tf
from tensorflow.python.data import Dataset

tf.logging.set_verbosity(tf.logging.ERROR)
pd.options.display.max_rows = 10
pd.options.display.float_format = '{:.1f}'.format

housing_dataframe = pd.read_csv("https://download.mlcc.google.com/mledu-datasets/california_housing_train.csv", sep=",")


def preprosses_feature(housing_dataframe):

  selected_feature = housing_dataframe[
   ["latitude",
    "longitude",
    "housing_median_age",
    "total_rooms",
    "total_bedrooms",
    "population",
    "households",
    "median_income"]]
  preprosses_feature = selected_feature.copy()
  preprosses_feature["room_per_person"] = (housing_dataframe["total_rooms"]/housing_dataframe["population"])
  return preprosses_feature

def preprosses_target(housing_dataframe):

  output_target = pd.DataFrame()
  output_target["median_house_value"] = (housing_dataframe["median_house_value"]/1000.0)
  return output_target

training_examples = preprosses_feature(housing_dataframe.head(12000))
training_targets = preprosses_target(housing_dataframe.head(12000))

validation_examples = preprosses_feature(housing_dataframe.tail(5000))
validation_targets = preprosses_target(housing_dataframe.tail(5000))  

print("training machine")
display.display(training_examples.describe())

print("target of machine")
display.display(training_targets.describe())

print("validation of housing value example")
display.display(validation_examples.describe())

print("validation of target")
display.display(validation_targets.describe())

correlation_dataframe = housing_dataframe.copy()
correlation_dataframe["target"] = training_targets["median_house_value"]
display.display(correlation_dataframe.corr())

def construct_feature_columns(input_features):

  return set([tf.feature_column.numeric_column(my_feature)
             for my_feature in input_features])
def my_input_fn(features, target, batch_size=1, shuffle=True, num_epochs=None):
  features = {key:np.array(value) for key,value in dict(features).iteams()}
  ds = Dataset.from_tensorn_slices((features,target))
  ds = da.batch(batch_size).reapeat(num_epochs)
  if shuffle:
    ds = ds.shuffle(10000)
  feature, lables = ds.make_one_short_iterator().get_next()
  return feature, lables

def train_model(
    learning_rate,
    steps,
    batch_size,
    training_examples,
    training_targets,
    validation_examples,
    validation_targets):
    
  periods = 10
  steps_per_period = steps / periods
    
  my_optimizer = tf.train.GradientDescentOptimizer(learning_rate = learning_rate)
  my_optimizer = tf.contrib.estimator.clip_gradients_by_norm(my_optimizer, 5.0)
  liner_regressor = tf.estimator.LinearRegressor(feature_columns=construct_feature_columns(training_examples),
                                                    optimizer = my_optimizer
                                                ) 
      
    
  training_input_fn = lambda: my_input_fn(training_examples,
                                           training_tragets["median_house_value"],
                                           batch_size = batch_size)
  predict_training_input_fn = lambda: my_input_fn(training_examples,
                                                   training_tragets["median_house_value"],
                                                   num_epoch = 1,
                                                   shuffle =  True)
  predict_validation_input_fn = lambda: my_input_fn(validation_examples,
                                                   validation_tragets["median_house_value"],
                                                   num_epoch = 1,
                                                   shuffle =  True)
    
  print("training on model.......")
  print("RMES (on training data):")
  training_rmse = []
  validation_rmse = []
  for period in range (0,periods):
      liner_regressor.train(
          input_fn=training_input_fn,
          steps=steps_per_period,
    )
      training_predictions = liner_regressor_predict(input_fn=predict_training_input_fn)
      training_predictions = np.array([item['prediction'][0] for item in training_prediction])
        
      validation_predictions = liner_regressor_predict(input_fn=predict_training_input_fn)
      validation_predictions = np.array([item['prediction'][0] for item in validation_prediction])
        
        
      training_root_mean_squred_error = math.sqrt(
          matrics.mean_squred_error(training_predictions, training_targets))
      validation_root_mean_squred_error = math.sqrt(
          matrics.mean_squred_error(validation_predictions, validation_targets))
        
      print("  period%02d : %0.2f" % (period, training_root_mean_squred_error))
      training_rmse.append(training_root_mean_squred_error)
      validation_rmse.append(validation_root_mean_squred_error)
  print("model training fineshed")
      
      
  plt.ylabel("RMSE")
  plt.xlabel("Periods")
  plt.title("Root Mean Squared Error vs. Periods")
  plt.tight_layout()
  plt.plot(training_rmse, label="training")
  plt.plot(validation_rmse, label="validation")
  plt.legend()

  return linear_regressor

minimal_features = [
  "median_income",
  "latitude",
]

minimal_training_examples = training_examples[minimal_features]
minimal_validation_examples = validation_examples[minimal_features]

_ = train_model(
    learning_rate=0.01,
    steps=500,
    batch_size=5,
    training_examples=minimal_training_examples,
    training_targets=training_targets,
    validation_examples=minimal_validation_examples,
    validation_targets=validation_targets)

training machine

,latitude,longitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,room_per_person
count,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0,12000.0
mean,34.6,-118.5,27.5,2655.7,547.1,1476.0,505.4,3.8,1.9
std,1.6,1.2,12.1,2258.1,434.3,1174.3,391.7,1.9,1.3
min,32.5,-121.4,1.0,2.0,2.0,3.0,2.0,0.5,0.0
25%,33.8,-118.9,17.0,1451.8,299.0,815.0,283.0,2.5,1.4
50%,34.0,-118.2,28.0,2113.5,438.0,1207.0,411.0,3.5,1.9
75%,34.4,-117.8,36.0,3146.0,653.0,1777.0,606.0,4.6,2.3
max,41.8,-114.3,52.0,37937.0,5471.0,35682.0,5189.0,15.0,55.2

target of machine

       median_house_value
count             12000.0
mean                198.0
std                 111.9
min                  15.0
25%                 117.1
50%                 170.5
75%                 244.4
max                 500.0

validation of housing value example

,latitude,longitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,room_per_person
count,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0
mean,38.1,-122.2,31.3,2614.8,521.1,1318.1,491.2,4.1,2.1
std,0.9,0.5,13.4,1979.6,388.5,1073.7,366.5,2.0,0.6
min,36.1,-124.3,1.0,8.0,1.0,8.0,1.0,0.5,0.1
25%,37.5,-122.4,20.0,1481.0,292.0,731.0,278.0,2.7,1.7
50%,37.8,-122.1,31.0,2164.0,424.0,1074.0,403.0,3.7,2.1
75%,38.4,-121.9,42.0,3161.2,635.0,1590.2,603.0,5.1,2.4
max,42.0,-121.4,52.0,32627.0,6445.0,28566.0,6082.0,15.0,18.3

validation of target

       median_house_value
count              5000.0
mean                229.5
std                 122.5
min                  15.0
25%                 130.4
50%                 213.0
75%                 303.2
max                 500.0

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,target
longitude,1.0,-0.9,-0.1,0.0,0.1,0.1,0.1,-0.0,-0.0,0.1
latitude,-0.9,1.0,0.0,-0.0,-0.1,-0.1,-0.1,-0.1,-0.1,-0.3
housing_median_age,-0.1,0.0,1.0,-0.4,-0.3,-0.3,-0.3,-0.1,0.1,0.1
total_rooms,0.0,-0.0,-0.4,1.0,0.9,0.9,0.9,0.2,0.1,0.1
total_bedrooms,0.1,-0.1,-0.3,0.9,1.0,0.9,1.0,-0.0,0.0,0.1
population,0.1,-0.1,-0.3,0.9,0.9,1.0,0.9,-0.0,-0.0,-0.0
households,0.1,-0.1,-0.3,0.9,1.0,0.9,1.0,0.0,0.1,0.1
median_income,-0.0,-0.1,-0.1,0.2,-0.0,-0.0,0.0,1.0,0.7,0.7
median_house_value,-0.0,-0.1,0.1,0.1,0.0,-0.0,0.1,0.7,1.0,1.0
target,0.1,-0.3,0.1,0.1,0.1,-0.0,0.1,0.7,1.0,1.0

training on model.......
RMES (on training data):

NameError: ignored

In [0]:
from __future__ import print_function